# .github/FUNDING.yml

github: mooncity        # If you get approved for GitHub Sponsors
patreon: james
open_collective: myproject
ko_fi: mooncity
tidelift: mooncity
liberapay: mooncity
issuehunt: mooncity
otechie: mooncity
custom: ["https://buymeacoffee.com/yourname", "https://yourwebsite.com/donate"]
